deviceName: "Arona"

http:
  bindHost: 127.0.0.1
  bindPort: 3000
  baseUrl: "http://example.com"

bridge:
  public: true

bridgeProvider:
  # OpenAI
  openai:
    enable: false
    # https://github.com/ai-tech-tw/openai
    baseUrl: "https://web-tech-tw.eu.org/openai/v1"
    apiKey: "YourGeminiApiKey"
    chatModel: "gpt-3.5-turbo"

  # LINE
  line:
    enable: false
    channelAccessToken: "YourChannelAccessToken"
    channelSecret: "YourChannelSecret"
    useNotify: false
    notifyClientId: "YourClientID"
    notifyClientSecret: "YourClientSecret"

  # Matrix
  matrix:
    enable: false
    homeserverUrl: "https://matrix.org"
    accessToken: "YourSecretAccessToken"

  # Discord
  discord:
    enable: false
    appId: "YourAppId"
    botToken: "YourBotToken"

  # Telegram
  telegram:
    enable: false
    botToken: "YourBotToken"
